---
resources:
  - name: security-cloudwatch-config-git
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/cyber-security-cloudwatch-config
      branch: concourse-pipeline

blocks:
  - config: &cloudwatch_build

      platform: linux

      image_resource:
        type: docker-image
        source:
            repository: gdscyber/concourse-worker-health
            tag: '1.2.1'

      inputs:
        - name: security-cloudwatch-config-git

jobs:
  - name: cloudwatch_tests
    plan:
      - get: security-cloudwatch-config-git
        trigger: true

      - task: test
        config:
          <<: *cloudwatch_build
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cd lambda/health_package
                make test
            dir: security-cloudwatch-config-git

  - name: cloudwatch_zip
    plan:
      - get: security-cloudwatch-config-git
        trigger: true
        passed:
          - cloudwatch_tests
      - task: zip
        config:
          <<: *cloudwatch_build
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cd lambda/health_package
                make zip
            dir: security-cloudwatch-config-git
