---
resources:
  - name: security-cloudwatch-config-git
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/cyber-security-cloudwatch-config
      branch: master

  - name: security-cloudwatch-config-git_docker
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/cyber-security-cloudwatch-config
      branch: master
      paths:
        - docker/Dockerfile
        - lambda/health_package/requirements.txt
        - lambda/health_package/requirements-dev.txt
        - lambda/health_package/Makefile
        - lambda/health_package/tox.ini

  - name: cloudwatch_docker
    type: docker-image
    source:
      repository: ((ecs_repo))

blocks:
  - &security-cloudwatch-config-git
    get: security-cloudwatch-config-git
    trigger: true

  - &cloudwatch_docker
    get: cloudwatch_docker
    trigger: true
    passed:
      - cloudwatch_build_docker_image

  - config: &cloudwatch_build

      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: ((ecs_repo))

      inputs:
        - name: security-cloudwatch-config-git

jobs:
  - name: cloudwatch_build_docker_image
    plan:
      - get: security-cloudwatch-config-git_docker
        trigger: true

      - put: cloudwatch_docker
        params:
          build: security-cloudwatch-config-git_docker
          tag_as_latest: true

  - name: cloudwatch_tests
    plan:
      - *security-cloudwatch-config-git
      - *cloudwatch_docker
      - task: test
        config:
          <<: *cloudwatch_build
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cd lambda/health_package
                make test
            dir: security-cloudwatch-config-git
