---
resources:
  - name: cyber-security-cloudwatch-config-git
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/cyber-security-cloudwatch-config
      branch: concourse-pipeline

  - name: cyber-security-terraform-git
    icon: github-circle
    type: git
    source:
      uri: git@github.com:alphagov/cyber-security-terraform.git
      branch: master
      private_key: ((cyber-security-terraform-deploy-key))
      paths:
        - service/cloudwatch-config/*

  - name: health-notification
    type: http-api
    source:
      uri: https://((health_host_test))/?alert_type=concourse$&alert_name=health
      method: POST
      headers:
        Authorization: "Bearer ((health_token_test))"
      json:
        service: "{service}"
        state: "{health}"
        message: "{message}"
        pipeline: "{BUILD_PIPELINE_NAME}"
        job: "{BUILD_JOB_NAME}"
        build_number: "{BUILD_NAME}"
      service: "health"

health_status_notify: &health_status_notify
  put: health-notification

resource_types:
  - name: http-api
    type: docker-image
    source:
      repository: aequitas/http-api-resource
      tag: latest

blocks:
  - config: &cloudwatch_build

      platform: linux

      image_resource:
        type: docker-image
        source:
            repository: gdscyber/concourse-worker-health
            tag: '1.2.8'

      inputs:
        - name: cyber-security-cloudwatch-config-git

jobs:
  - name: cloudwatch_test
    plan:
      - get: cyber-security-cloudwatch-config-git
        trigger: true
      - get: cyber-security-terraform-git
        trigger: false

      - task: test
        config:
          <<: *cloudwatch_build
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cd lambda/health_package
                make test
                echo "Tests completed"
            dir: cyber-security-cloudwatch-config-git
        on_success:
          <<: *health_status_notify
          params:
            message: "Health package test passed"
            health: healthy
        on_failure:
          <<: *health_status_notify
          params:
            message: "Health package test failed"
            health: unhealthy

  - name: cloudwatch_staging_deploy
    plan:
      - get: cyber-security-cloudwatch-config-git
        trigger: true
        passed:
          - cloudwatch_test
      - get: cyber-security-terraform-git
        trigger: false

      - task: terraform_deploy_keys
        config:
          <<: *cloudwatch_build
          outputs:
          - name: ssh
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cat > deploy_key <<'EOF'
                ((cyber-security-terraform-deploy-key))
                EOF
                echo "Host github.com" > config
                echo "  IdentityFile {workdir}/deploy_key" >> config
                echo "  StrictHostKeyChecking no" >> config
                chmod 400 deploy_key
            dir: ssh

      - task: zip
        config:
          <<: *cloudwatch_build
          outputs:
          - name: lambda_package
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cd lambda/health_package
                make zip
                mv health_package.zip ../../../lambda_package
                echo "Built zip file lambda distribution"
                ls ../../..
            dir: cyber-security-cloudwatch-config-git

      - task: terraform_account_validate
        config:
          <<: *cloudwatch_build
          inputs:
          - name: cyber-security-cloudwatch-config-git
          - name: cyber-security-terraform-git
          - name: ssh
          - name: lambda_package
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                cd ..
                cp lambda_package/health_package.zip cyber-security-cloudwatch-config-git/lambda/health_package
                cat ssh/config
                workdir=$(pwd)
                mkdir /root/.ssh
                sed 's+{workdir}+'"$workdir"'/ssh+g' ssh/config > /root/.ssh/config
                cat /root/.ssh/config
                test_run_account=$(ls cyber-security-terraform-git/service/cloudwatch-config/per_account/deployments | head -1)
                ln -fs ${workdir}/cyber-security-terraform-git/service/cloudwatch-config/per_account/deployments ${workdir}/cyber-security-cloudwatch-config-git/terraform/per_account
                cd cyber-security-cloudwatch-config-git
                cd terraform/per_account/deployable

                target_arn="arn:aws:iam::${test_run_account}:role/HealthConcourseWorkerRole"
                source sts-assume-role.sh $target_arn
                source sts-get-caller-identity.sh

                terraform init -reconfigure -backend-config=../deployments/$test_run_account/backend.tfvars
                terraform validate
                echo "Terraform valid"
            dir: cyber-security-cloudwatch-config-git
        on_success:
          <<: *health_status_notify
          params:
            message: "The account terraform has been validated"
            health: healthy
        on_failure:
          <<: *health_status_notify
          params:
            message: "The account terraform validation has failed"
            health: unhealthy

      - task: create_alarm_config
        config:
          <<: *cloudwatch_build
          inputs:
            - name: cyber-security-cloudwatch-config-git
            - name: cyber-security-terraform-git
          outputs:
            - name: deployments
          run:
            path: /bin/bash
            args:
              - -exc
              - |

                monitored_accounts=$(ls ../cyber-security-terraform-git/service/cloudwatch-config/per_account/deployments)

                for account_id in $monitored_accounts; do

                 echo "Test assume role"
                 target_arn="arn:aws:iam::${account_id}:role/HealthConcourseWorkerRole"
                 source sts-assume-role.sh $target_arn
                 source sts-get-caller-identity.sh

                 if [[ $account_id == $AWS_ASSUMED_ACCOUNT_ID ]]; then
                  echo $AWS_ASSUMED_ACCOUNT_ID
                  echo $AWS_ASSUMED_ROLE_ARN

                  cd lambda/health_package
                  make run
                  cd ../..
                 else
                  echo "FAILED TO ASSUME ${account_id}"
                 fi
                done

                pwd
                ls terraform/per_account/deployments
                cp -r terraform/per_account/deployments/* ../deployments
                ls -l ../deployments

            dir: cyber-security-cloudwatch-config-git

      - task: deploy_terraform
        config:
          <<: *cloudwatch_build
          inputs:
            - name: cyber-security-cloudwatch-config-git
            - name: cyber-security-terraform-git
            - name: lambda_package
            - name: deployments
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                monitored_accounts=$(ls ../deployments)

                for account_id in $monitored_accounts; do
                  ls ../deployments/${account_id}
                  env=$(grep DEF_ENVIRONMENT service/cloudwatch-config/per_account/deployments/${account_id}/apply.tfvars | tr '"' ' ' | awk {' print $3 '})
                  echo "${account_id} is a ${env} environment"
                done
            dir: cyber-security-terraform-git
